services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_POSTGRESDB_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRESDB_PASSWORD}
      POSTGRES_DB: ${DB_POSTGRESDB_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    image: n8nio/n8n:latest
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5678:5678"
    env_file:
      - .env
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: ${DB_POSTGRESDB_DATABASE}
      DB_POSTGRESDB_USER: ${DB_POSTGRESDB_USER}
      DB_POSTGRESDB_PASSWORD: ${DB_POSTGRESDB_PASSWORD}
      N8N_SECURE_COOKIE: 'false'
      N8N_DIAGNOSTICS_ENABLED: 'false'
      N8N_VERSION_NOTIFICATIONS_ENABLED: 'false'
      # carrega custom nodes de ~/.n8n/custom
      N8N_CUSTOM_EXTENSIONS: /home/node/.n8n/custom
    volumes:
      - ./custom:/home/node/.n8n/custom
      - ./.n8n:/home/node/.n8n

volumes:
  pgdata: